export const tokens = {
  colors: {
    primary: 'var(--ht-green)',
    primaryDark: 'var(--ht-green-dark)',
    warning: 'var(--ht-amber)',
    warningDark: 'var(--ht-amber-dark)',
    textPrimary: 'var(--text-primary)',
    textSecondary: 'var(--text-secondary)',
    textMuted: 'var(--text-muted)',
    textOnPrimary: 'var(--text-on-primary)',
    surface: 'var(--bg-surface)',
    background: 'var(--bg-primary)',
    border: 'var(--border-color)',
    success: 'var(--ht-success-text)',
    error: 'var(--ht-error-text)',
    badgeBgSuccess: 'var(--ht-success-bg)',
    badgeBgError: 'var(--ht-error-bg)',
    info: 'var(--ht-green)',
    badgeBgInfo: 'var(--bg-surface)',
    warningText: 'var(--ht-warning-text)',
    warningBg: 'var(--ht-warning-bg)',
    warningBorder: 'var(--ht-warning-border)',
    warningTint: 'var(--ht-warning-tint)',
    warningStrong: 'var(--ht-warning-strong)',
    warningSurfaceBg: 'var(--warning-surface-bg)',
    warningSurfaceBgSoft: 'var(--warning-surface-bg-soft)',
    warningSurfaceBorder: 'var(--warning-surface-border)',
    warningSurfaceText: 'var(--warning-surface-text)',
    warningStrongBg: 'var(--warning-strong-bg)',
    infoText: 'var(--ht-info-text)',
    infoBg: 'var(--ht-info-bg)',
    infoAccentBg: 'var(--info-accent-bg)',
    infoAccentText: 'var(--info-accent-text)',
    successTint: 'var(--ht-success-tint)',
    errorBorder: 'var(--ht-error-border)',
    successBorder: 'var(--ht-success-border)',
    surfaceSubtle: 'var(--ht-surface-subtle)',
    surfaceSuccessSoft: 'var(--ht-surface-success-soft)',
    surfaceHeaderSubtle: 'var(--surface-header-subtle)',
    surfaceRowAlt: 'var(--surface-row-alt)',
    surfaceNeutralSoft: 'var(--surface-neutral-soft)',
    errorSurfaceSoft: 'var(--error-surface-bg-soft)',
    violetAccentBg: 'var(--violet-accent-bg)',
    violetAccentText: 'var(--violet-accent-text)',
    violetStrongBg: 'var(--violet-strong-bg)',
    violetStrongText: 'var(--violet-strong-text)',
    taskTabBg: 'var(--ht-task-tab-bg)',
    taskTabText: 'var(--ht-task-tab-text)',
    taskBlockedBg: 'var(--ht-task-blocked-bg)',
    taskBlockedText: 'var(--ht-task-blocked-text)',
    progressTrack: 'var(--ht-progress-track)',
    progressComplete: 'var(--ht-progress-complete)',
    white: '#FFFFFF',
  },
  radius: {
    sm: 'var(--radius-sm)',
    md: 'var(--radius-md)',
    lg: 'var(--radius-lg)',
    xl: 'var(--radius-xl)'
  },
  shadow: {
    sm: 'var(--shadow-sm)',
    md: 'var(--shadow-md)',
    auth: 'var(--auth-card-shadow)',
  },
  overlay: {
    backdropGradient: 'linear-gradient(180deg, rgba(8, 15, 30, 0.72) 0%, rgba(4, 10, 24, 0.82) 100%)',
    backdropBlur: '16px',
    softBackdrop: 'rgba(15, 23, 42, 0.42)',
    drawerShadow: '-18px 0 40px rgba(15, 23, 42, 0.16)',
    modalShadow: '0 24px 80px rgba(2, 6, 23, 0.45)',
    toastBlur: '8px',
  },
  interaction: {
    focusRing: 'var(--focus-ring-color)',
    shadowLg: 'var(--shadow-interactive-lg)',
    shadowMd: 'var(--shadow-interactive-md)',
    dropShadow: 'var(--shadow-drop-target)',
  },
  surface: {
    panelGradient: 'var(--panel-gradient-bg)',
    heroGradient: 'var(--hero-card-bg)',
    heroGradientSubtle: 'var(--hero-card-bg-subtle)',
    authCanvas: 'var(--auth-shell-bg)',
    drawerHeader: 'var(--drawer-header-bg)',
    detail: 'var(--ht-surface-subtle)',
    sheen: 'var(--surface-sheen)',
    chip: 'var(--surface-chip-bg)',
    empty: 'var(--surface-empty-bg)',
    skeleton: 'var(--surface-skeleton-bg)',
    sticky: 'var(--surface-sticky-bg)',
    badge: 'var(--surface-badge-bg)',
    badgeStrong: 'var(--surface-badge-bg-strong)',
  },
  spacing: {
    xxs: '2px',
    xs: '4px',
    xsPlus: '6px',
    sm: '8px',
    smPlus: '10px',
    md: '12px',
    mdPlus: '14px',
    lg: '16px',
    lgPlus: '18px',
    xl: '24px',
    xlPlus: '20px',
    xxl: '28px',
    xxxl: '32px',
  },
  shell: {
    sectionGap: '24px',
  },
  fontSize: {
    xxs: 'var(--font-size-xxs)',
    xs: 'var(--font-size-xs)',
    sm: 'var(--font-size-sm)',
    md: 'var(--font-size-md)',
    base: 'var(--font-size-base)',
    lg: 'var(--font-size-lg)',
    xl: 'var(--font-size-xl)',
    title: 'var(--font-size-title)',
    displaySm: 'var(--font-size-display-sm)',
    displayMd: 'var(--font-size-display-md)',
    displayLg: 'var(--font-size-display-lg)',
    displayXl: 'var(--font-size-display-xl)',
  },
  zIndex: {
    base: 0,
    sticky: 10,
    dropdown: 200,
    popover: 300,
    toast: 900,
    overlayBackdrop: 1000,
    modal: 1010,
    drawer: 1020,
    detail: 1030,
    modalTop: 1030,
    emergency: 1100,
  }
} as const;
